server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  config:
    import:
      - "optional:configserver:http://localhost:8888"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  cloud:
    config:
      name: gameinfo
    gateway:
      server:
        webflux:
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: Spring Cloud Gateway WebFlux Global Filter
                preLogger: true
                postLogger: true
          routes:
            # 유저 서비스 Actuator
            - id: user-service-actuator
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/actuator/**
              filters:
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            # 유저 서비스
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/info/**
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter
            # 유저 포인트 증감/차감
            - id: user-service-point
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/point/**
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter
            # 회원가입
            - id: user-service-register
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/users
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            # 로그인
            - id: user-service-login
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/login
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            # 제품 서비스
            - id: catalog-service
              uri: lb://CATALOG-SERVICE
              predicates:
                - Path=/catalog-service/**
            # 주문 서비스
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-service/**
              filters:
                - AuthorizationHeaderFilter
            # 게임 키 서비스
            - id: key-inventory-service
              uri: lb://KEY-INVENTORY-SERVICE
              predicates:
                - Path=/key-inventory/**
              filters:
                - AuthorizationHeaderFilter
            # 결제 서비스
            - id: pay-service-process
              uri: lb://PAY-SERVICE
              predicates:
                - Path=/payment-service/payment/success, /payment-service/payment/cancel, /payment-service/payment/fail
            # 결제 서비스
            - id: pay-service
              uri: lb://PAY-SERVICE
              predicates:
                - Path=/payment-service/**
              filters:
                - AuthorizationHeaderFilter
            # 장바구니 서비스
            - id: order-service-cart
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/cart-service/**
              filters:
                - AuthorizationHeaderFilter
            # 찜하기 서비스
            - id: user-service-wish
              uri: lb://USER-SERVICE
              predicates:
                - Path=/wish-service/**
              filters:
                - AuthorizationHeaderFilter
            # 토큰 재발급
            - id: user-service-refresh
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/auth/refresh
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - info
          - httpexchanges
          - busrefresh